name: PrettyDate
authors: thinkphp,fitorec
current: v1.1
category: utilities
tags: [date,iso8601,time]
docs: https://github.com/thinkphp/prettydate/blob/master/Docs/PrettyDate.md
demo: http://thinkphp.github.com/prettydate/
